name: hello workflow
on: workflow_dispatch
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: print message
        run: |
          echo Github actions
          echo Multiline command
